###############################################################################
# NRDOT Configuration with attributes for trace awareness                     #
###############################################################################

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

receivers:
  hostmetrics:
    root_path: "/hostfs"
    collection_interval: "30s"
    scrapers:
      processes: {}
      process:
        metrics:
          process.cpu.utilization: {enabled: true}
          process.memory.usage: {enabled: true}
          process.disk.io: {enabled: true}
        include: {match_type: regexp, names: [".*"]}
        exclude: {match_type: regexp, names: ["$^"]}

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 250
    spike_limit_mib: 150
  
  metricstransform/drop_idle_state:
    transforms:
      - include: ^process\.cpu\.utilization$
        action: update
        operations:
          - action: delete_label_value
            label: state
            label_value: idle

  metricstransform/rename_util:
    transforms:
      - include: ^process\.cpu\.utilization$
        action: update
        operations:
          - action: update_label
            label: state
            new_label: cpu_state
      - include: ^process\.memory\.usage$
        action: update
        operations:
          - action: update_label
            label: state
            new_label: memory_state
  
  # Dedicated trace-aware attributes for all metrics
  attributes/trace_aware:
    actions:
      - key: trace.aware.collector
        value: "true"
        action: upsert
      - key: trace.aware.version
        value: "1.0"
        action: upsert
        
  # Profile-specific attributes
  attributes/ultra:
    actions:
      - key: deployment.environment
        value: "${env:OTEL_DEPLOYMENT_ENVIRONMENT:-production}"
        action: upsert
      - key: service.name
        value: "${env:OTEL_SERVICE_NAME_HOST_METRICS:-nrdot-collector-host}-ultra"
        action: upsert
      - key: collector.profile
        value: "ultra"
        action: upsert
      - key: trace.aware.profile
        value: "ultra"
        action: upsert
    
  attributes/balanced:
    actions:
      - key: deployment.environment
        value: "${env:OTEL_DEPLOYMENT_ENVIRONMENT:-production}"
        action: upsert
      - key: service.name
        value: "${env:OTEL_SERVICE_NAME_HOST_METRICS:-nrdot-collector-host}-balanced"
        action: upsert
      - key: collector.profile
        value: "balanced"
        action: upsert
      - key: trace.aware.profile
        value: "balanced"
        action: upsert
    
  attributes/optimized:
    actions:
      - key: deployment.environment
        value: "${env:OTEL_DEPLOYMENT_ENVIRONMENT:-production}"
        action: upsert
      - key: service.name
        value: "${env:OTEL_SERVICE_NAME_HOST_METRICS:-nrdot-collector-host}-optimized"
        action: upsert
      - key: collector.profile
        value: "optimized"
        action: upsert
      - key: trace.aware.profile
        value: "optimized"
        action: upsert
    
  attributes/lean:
    actions:
      - key: deployment.environment
        value: "${env:OTEL_DEPLOYMENT_ENVIRONMENT:-production}"
        action: upsert
      - key: service.name
        value: "${env:OTEL_SERVICE_NAME_HOST_METRICS:-nrdot-collector-host}-lean"
        action: upsert
      - key: collector.profile
        value: "lean"
        action: upsert
      - key: trace.aware.profile
        value: "lean"
        action: upsert
    
  attributes/micro:
    actions:
      - key: deployment.environment
        value: "${env:OTEL_DEPLOYMENT_ENVIRONMENT:-production}"
        action: upsert
      - key: service.name
        value: "${env:OTEL_SERVICE_NAME_HOST_METRICS:-nrdot-collector-host}-micro"
        action: upsert
      - key: collector.profile
        value: "micro"
        action: upsert
      - key: trace.aware.profile
        value: "micro"
        action: upsert
  
  cumulativetodelta: {}
  
  resourcedetection:
    detectors: [system]
  
  batch:
    send_batch_size: 8192
    timeout: 10s

exporters:
  otlphttp:
    endpoint: "${env:OTEL_EXPORTER_OTLP_ENDPOINT:-https://otlp.nr-data.net}"
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}
    compression: zstd
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 10000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 5m

  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "debug"
      development: true
      encoding: console
    metrics:
      level: "detailed"
      address: "0.0.0.0:8888"
  
  extensions: [health_check]
  
  pipelines:
    metrics/ultra:
      receivers: [hostmetrics]
      processors:
        [memory_limiter,
         metricstransform/drop_idle_state,
         metricstransform/rename_util,
         attributes/trace_aware,
         attributes/ultra,
         cumulativetodelta,
         resourcedetection,
         batch]
      exporters: [debug, otlphttp]
      
    metrics/balanced:
      receivers: [hostmetrics]
      processors:
        [memory_limiter,
         metricstransform/drop_idle_state,
         metricstransform/rename_util,
         attributes/trace_aware,
         attributes/balanced,
         cumulativetodelta,
         resourcedetection,
         batch]
      exporters: [debug, otlphttp]
      
    metrics/optimized:
      receivers: [hostmetrics]
      processors:
        [memory_limiter,
         metricstransform/drop_idle_state,
         metricstransform/rename_util,
         attributes/trace_aware,
         attributes/optimized,
         cumulativetodelta,
         resourcedetection,
         batch]
      exporters: [debug, otlphttp]
      
    metrics/lean:
      receivers: [hostmetrics]
      processors:
        [memory_limiter,
         metricstransform/drop_idle_state,
         metricstransform/rename_util,
         attributes/trace_aware,
         attributes/lean,
         cumulativetodelta,
         resourcedetection,
         batch]
      exporters: [debug, otlphttp]
      
    metrics/micro:
      receivers: [hostmetrics]
      processors:
        [memory_limiter,
         metricstransform/drop_idle_state,
         metricstransform/rename_util,
         attributes/trace_aware,
         attributes/micro,
         cumulativetodelta,
         resourcedetection,
         batch]
      exporters: [debug, otlphttp]