apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: nrdot-collector-config
  namespace: observability
  files:
  - config.yaml=../../../../config.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: nrdot-collector-host
    namespace: observability
  patch: |-
    [
      {
        "op": "replace",
        "path": "/spec/template/spec/containers/0/env/9/value",
        "value": "ultra"
      },
      {
        "op": "replace",
        "path": "/spec/template/spec/containers/0/env/10/value",
        "value": "true"
      },
      {
        "op": "replace",
        "path": "/spec/template/spec/containers/0/env/11/value",
        "value": "false"
      }
    ]