receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 1s
    
  reservoir_sampler:
    size_k: 5000
    window_duration: "60s"
    checkpoint_path: "/var/otelpersist/reservoir.db"
    checkpoint_interval: "10s"
    trace_aware: true
    trace_buffer_max_size: 100000
    trace_buffer_timeout: "30s"
    db_compaction_schedule_cron: "0 2 * * 0"
    db_compaction_target_size: 104857600

exporters:
  logging:
    verbosity: normal
    
  otlp:
    endpoint: prometheus:8888
    tls:
      insecure: true
  
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    namespace: pte

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, reservoir_sampler]
      exporters: [logging, otlp]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]
  
  extensions: [health_check, pprof, zpages]

  telemetry:
    logs:
      level: info
    metrics:
      level: detailed