version: '3.8'

services:
  nrdot:
    image: newrelic/nrdot-collector-host:1.1.0
    container_name: nrdot-collector
    # pid: host # Subject to macOS/Windows limitations for host process visibility
    # network_mode: host # Use for Linux if simple; for macOS/Windows, prefer port mapping below
    ports:
      - "${OTEL_COLLECTOR_HEALTH_CHECK_PORT:-13133}:${OTEL_COLLECTOR_HEALTH_CHECK_PORT:-13133}"
    volumes:
      - /:/hostfs:ro # For hostmetrics. Linux users can refine this.
      # Don't mount /etc directly as it causes conflicts with container setup
      - ./config/trace-aware-config.yaml:/etc/nrdot-collector-host/config.yaml:ro
    environment:
      # License Keys for different profiles
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_LICENSE_KEY_ULTRA=${NEW_RELIC_LICENSE_KEY_ULTRA:-${NEW_RELIC_LICENSE_KEY}}
      - NEW_RELIC_LICENSE_KEY_BALANCED=${NEW_RELIC_LICENSE_KEY_BALANCED:-${NEW_RELIC_LICENSE_KEY}}
      - NEW_RELIC_LICENSE_KEY_OPTIMIZED=${NEW_RELIC_LICENSE_KEY_OPTIMIZED:-${NEW_RELIC_LICENSE_KEY}}
      - NEW_RELIC_LICENSE_KEY_LEAN=${NEW_RELIC_LICENSE_KEY_LEAN:-${NEW_RELIC_LICENSE_KEY}}
      - NEW_RELIC_LICENSE_KEY_MICRO=${NEW_RELIC_LICENSE_KEY_MICRO:-${NEW_RELIC_LICENSE_KEY}}
      
      # OTEL Exporter Configuration
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-https://otlp.nr-data.net}
      - OTEL_EXPORTER_OTLPHTTP_LOG_DETAILED_RESPONSE=true
      - OTEL_EXPORTER_OTLPHTTP_TRACES_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-https://otlp.nr-data.net}/v1/traces
      - OTEL_EXPORTER_OTLPHTTP_METRICS_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-https://otlp.nr-data.net}/v1/metrics
      - OTEL_LOG_LEVEL=debug
      
      # Health Check
      - OTEL_COLLECTOR_HEALTH_CHECK_PORT=${OTEL_COLLECTOR_HEALTH_CHECK_PORT:-13133}
      
      # Host Path
      - HOST_ROOT_PATH=${HOST_ROOT_PATH:-/hostfs}
      
      # Profile Selection - Enable all profiles by default
      - NR_USE_BALANCED=true
      - NR_USE_ULTRA=true
      - NR_USE_OPTIMIZED=true
      - NR_USE_LEAN=true
      - NR_USE_MICRO=true
      
      # Collection Intervals
      - ULTRA_FAST_INTERVAL=${ULTRA_FAST_INTERVAL:-5s}
      - ULTRA_MEDIUM_INTERVAL=${ULTRA_MEDIUM_INTERVAL:-30s}
      - ULTRA_SLOW_INTERVAL=${ULTRA_SLOW_INTERVAL:-60s}
      - BALANCED_INTERVAL=${BALANCED_INTERVAL:-30s}
      - OPTIMIZED_INTERVAL=${OPTIMIZED_INTERVAL:-60s}
      - LEAN_INTERVAL=${LEAN_INTERVAL:-120s}
      - MICRO_INTERVAL=${MICRO_INTERVAL:-300s}
      
      # Entity Information
      - OTEL_DEPLOYMENT_ENVIRONMENT=${OTEL_DEPLOYMENT_ENVIRONMENT:-production}
      - OTEL_SERVICE_NAME_HOST_METRICS=${OTEL_SERVICE_NAME_HOST_METRICS:-nrdot-collector-host}
      
      # Queue and Batch Settings
      - OTLP_SENDING_QUEUE_SIZE=${OTLP_SENDING_QUEUE_SIZE:-10000}
      - OTLP_SENDING_QUEUE_CONSUMERS=${OTLP_SENDING_QUEUE_CONSUMERS:-4}
      - BATCH_SEND_SIZE=${BATCH_SEND_SIZE:-8192}
      - BATCH_TIMEOUT=${BATCH_TIMEOUT:-10s}
      
      # Memory Limiter Settings
      - NEW_RELIC_MEMORY_LIMIT_MIB=${NEW_RELIC_MEMORY_LIMIT_MIB:-250}
      - NEW_RELIC_MEMORY_SPIKE_LIMIT_MIB=${NEW_RELIC_MEMORY_SPIKE_LIMIT_MIB:-150}
      
      # Optional Process Filtering
      - PROCESS_INCLUDE=.*
      - PROCESS_EXCLUDE=NOMATCH_PATTERN_XYZ
      
      # Logging
      - OTEL_LOG_LEVEL=${OTEL_LOG_LEVEL:-debug}
    
    restart: unless-stopped
    # For production with Docker Compose, define resource limits:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M