version: '3.8'

services:
  entity-fixed-collector:
    image: otel/opentelemetry-collector:0.125.0
    container_name: entity-fixed-collector
    # pid: host # Subject to macOS/Windows limitations for host process visibility
    ports:
      - "13133:13133" # Health Check
    volumes:
      - /:/hostfs:ro # For hostmetrics. Linux users can refine this.
      - ./config/entity-fixed-config.yaml:/etc/otel/config.yaml:ro
    environment:
      # License Keys
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      
      # Entity Synthesis Variables
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=delta
      - OTEL_DEPLOYMENT_ENVIRONMENT=production
      - OTEL_SERVICE_NAME=otel-collector-host
      - OTEL_RESOURCE_ATTRIBUTES=host.name=${HOSTNAME},entity.type=HOST
      
      # OTEL Exporter Configuration
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.nr-data.net
      - OTEL_EXPORTER_OTLPHTTP_LOG_DETAILED_RESPONSE=true
      
      # Host Path
      - HOST_ROOT_PATH=/hostfs
      
      # Collection Intervals (entity-fixed config uses 30s by default)
      - COLLECTION_INTERVAL=30s
      
      # Enable machine-id detection
      - ENABLE_MACHINE_ID=true
      
      # Logging
      - OTEL_LOG_LEVEL=info
    
    command: ["--config=/etc/otel/config.yaml"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M