networks:
  demo_net: {}

services:
  ###############################################################################
  # Demo Applications
  ###############################################################################
  alpine:
    image: alpine:latest
    command: sh -c "while true; do echo 'Running demo...'; sleep 60; done"
    networks: [demo_net]

  ###############################################################################
  # NRDOT host collectors for each profile (running in parallel)
  ###############################################################################
  collector-ultra:
    image: newrelic/nrdot-collector-host:1.1.0
    container_name: demo-ultra-collector
    ports: 
      - "8889:8888"  # For prometheus metrics
    volumes:
      - ./config.yaml:/etc/otel/config.yaml:ro
    environment:
      - BENCHMARK_PROFILE=ultra
      - DEMO_ID=${DEMO_ID:-demo-local}-ultra
      - NR_USE_ULTRA=true
      - NR_USE_BALANCED=false
      - NR_USE_OPTIMIZED=false
      - NR_USE_LEAN=false
      - NR_USE_MICRO=false
      - NEW_RELIC_LICENSE_KEY=${NR_KEY:-replace_me}
      - NEW_RELIC_METADATA_DEMO_ID=${DEMO_ID:-demo-local}-ultra
    command: --config /etc/otel/config.yaml

  collector-balanced:
    image: newrelic/nrdot-collector-host:1.1.0
    container_name: demo-balanced-collector
    ports: 
      - "8890:8888"  # For prometheus metrics
    volumes:
      - ./config.yaml:/etc/otel/config.yaml:ro
    environment:
      - BENCHMARK_PROFILE=balanced
      - DEMO_ID=${DEMO_ID:-demo-local}-balanced
      - NR_USE_ULTRA=false
      - NR_USE_BALANCED=true
      - NR_USE_OPTIMIZED=false
      - NR_USE_LEAN=false
      - NR_USE_MICRO=false
      - NEW_RELIC_LICENSE_KEY=${NR_KEY:-replace_me}
      - NEW_RELIC_METADATA_DEMO_ID=${DEMO_ID:-demo-local}-balanced
    command: --config /etc/otel/config.yaml

  collector-optimized:
    image: newrelic/nrdot-collector-host:1.1.0
    container_name: demo-optimized-collector
    ports: 
      - "8891:8888"  # For prometheus metrics
    volumes:
      - ./config.yaml:/etc/otel/config.yaml:ro
    environment:
      - BENCHMARK_PROFILE=optimized
      - DEMO_ID=${DEMO_ID:-demo-local}-optimized
      - NR_USE_ULTRA=false
      - NR_USE_BALANCED=false
      - NR_USE_OPTIMIZED=true
      - NR_USE_LEAN=false
      - NR_USE_MICRO=false
      - NEW_RELIC_LICENSE_KEY=${NR_KEY:-replace_me}
      - NEW_RELIC_METADATA_DEMO_ID=${DEMO_ID:-demo-local}-optimized
    command: --config /etc/otel/config.yaml

  collector-lean:
    image: newrelic/nrdot-collector-host:1.1.0
    container_name: demo-lean-collector
    ports: 
      - "8892:8888"  # For prometheus metrics
    volumes:
      - ./config.yaml:/etc/otel/config.yaml:ro
    environment:
      - BENCHMARK_PROFILE=lean
      - DEMO_ID=${DEMO_ID:-demo-local}-lean
      - NR_USE_ULTRA=false
      - NR_USE_BALANCED=false
      - NR_USE_OPTIMIZED=false
      - NR_USE_LEAN=true
      - NR_USE_MICRO=false
      - NEW_RELIC_LICENSE_KEY=${NR_KEY:-replace_me}
      - NEW_RELIC_METADATA_DEMO_ID=${DEMO_ID:-demo-local}-lean
    command: --config /etc/otel/config.yaml

  collector-micro:
    image: newrelic/nrdot-collector-host:1.1.0
    container_name: demo-micro-collector
    ports: 
      - "8893:8888"  # For prometheus metrics
    volumes:
      - ./config.yaml:/etc/otel/config.yaml:ro
    environment:
      - BENCHMARK_PROFILE=micro
      - DEMO_ID=${DEMO_ID:-demo-local}-micro
      - NR_USE_ULTRA=false
      - NR_USE_BALANCED=false
      - NR_USE_OPTIMIZED=false
      - NR_USE_LEAN=false
      - NR_USE_MICRO=true
      - NEW_RELIC_LICENSE_KEY=${NR_KEY:-replace_me}
      - NEW_RELIC_METADATA_DEMO_ID=${DEMO_ID:-demo-local}-micro
    command: --config /etc/otel/config.yaml