extensions:
  health_check: {}

receivers:
  hostmetrics:
    root_path: ${env:HOST_ROOT_PATH:-/hostfs}
    collection_interval: 30s
    scrapers:
      cpu: {}
      memory: {}
      load: {}
      # Disabled filesystem temporarily
      # filesystem:
      #   exclude_mount_points:
      #     match_type: regexp
      #     mount_points:
      #       - "^/var/lib/kubelet/pods/.+/volume-subpaths/"

processors:
  batch: {}
  
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
      
  attributes:
    actions:
      - key: benchmark.demo_id
        value: "test-minimal"
        action: upsert

exporters:
  otlphttp:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT:-https://otlp.nr-data.net}
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}
    compression: ${env:OTEL_EXPORTER_OTLP_COMPRESSION:-zstd}
  logging:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, attributes, batch]
      exporters: [otlphttp, logging]