# Configuration for trace-aware reservoir sampling
# This file defines the sampling parameters and processor behavior

# Defines how many traces to keep in the reservoir
# For small environments: 1000
# For medium environments: 5000
# For large environments: 10000+
size_k: 5000

# Duration of each sampling window
# Shorter windows (30s) provide more frequent sampling updates
# Longer windows (120s) reduce processing overhead
window_duration: "60s"

# How often to save checkpoint state to disk
# More frequent (5s) improves durability at the cost of I/O
# Less frequent (30s) reduces I/O but increases potential data loss on crash
checkpoint_interval: "10s"

# Whether to keep entire traces together (recommended)
trace_aware: true

# Maximum number of spans to buffer while waiting for trace completion
# Higher values handle larger traces but use more memory
# Lower values are suitable for simpler applications with smaller traces
trace_buffer_max_size: 100000

# Maximum time to wait for spans in a trace
# Longer times (60s) better handle traces with high latency spans
# Shorter times (10s) limit memory usage for incomplete traces
trace_buffer_timeout: "30s"

# Database compaction schedule (cron format)
# Compacts the BoltDB file to reclaim space
# Default: Weekly at 2 AM on Sunday
db_compaction_schedule_cron: "0 2 * * 0"

# Kubernetes Settings
# ------------------
# Persistence is REQUIRED for checkpointing
persistence:
  enabled: true
  size: 1Gi

# Paths
# -----
# IMPORTANT: Must match the persistent volume path in your environment
checkpoint_path: "/var/otelpersist/reservoir.db"