apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OTEL_DEPLOYMENT_NAME }}
  namespace: {{ .NAMESPACE }}
  labels:
    app: otel-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-monitor
  template:
    metadata:
      labels:
        app: otel-monitor
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: otel-collector
        image: {{ .OTEL_IMAGE }}
        command: ["/otelcol-contrib", "--config=/etc/otelcol-contrib/config.yaml"]
        env:
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secrets
              key: license-key
        volumeMounts:
        - name: otel-config-vol
          mountPath: /etc/otelcol-contrib/config.yaml
          subPath: config.yaml
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        securityContext:
          privileged: true

      volumes:
      - name: otel-config-vol
        configMap:
          name: otel-config
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: rootfs
        hostPath:
          path: /