apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .PVC_NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .PVC_SIZE }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OTEL_PROCESSOR_DEPLOYMENT_NAME }}
  namespace: {{ .NAMESPACE }}
  labels:
    app: otel-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-processor
  template:
    metadata:
      labels:
        app: otel-processor
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: otel-collector
        image: {{ .OTEL_IMAGE }}
        # In a real environment, you would build a custom image with your processor
        # This is a placeholder for the actual implementation
        command: ["/otelcol-contrib", "--config=/etc/otelcol-contrib/config.yaml"]
        env:
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secrets
              key: license-key
        ports:
        - name: otlp-grpc
          containerPort: {{ .OTLP_GRPC_PORT }}
          hostPort: {{ .OTLP_GRPC_PORT }}
        - name: otlp-http
          containerPort: {{ .OTLP_HTTP_PORT }}
          hostPort: {{ .OTLP_HTTP_PORT }}
        volumeMounts:
        - name: otel-processor-config-vol
          mountPath: /etc/otelcol-contrib/config.yaml
          subPath: config.yaml
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: checkpoint-volume
          mountPath: /data/checkpoint
        securityContext:
          privileged: true

      volumes:
      - name: otel-processor-config-vol
        configMap:
          name: otel-processor-config
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: rootfs
        hostPath:
          path: /
      - name: checkpoint-volume
        persistentVolumeClaim:
          claimName: {{ .PVC_NAME }}
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .NAMESPACE }}
spec:
  selector:
    app: otel-processor
  ports:
  - name: otlp-grpc
    port: {{ .OTLP_GRPC_PORT }}
    targetPort: {{ .OTLP_GRPC_PORT }}
  - name: otlp-http
    port: {{ .OTLP_HTTP_PORT }}
    targetPort: {{ .OTLP_HTTP_PORT }}