apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrdot-config
  namespace: observability
data:
  config.yaml: |
    # This content will be replaced by the ConfigMap generator in Kustomize
    # The actual configuration comes from the root config.yaml file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrdot-collector-ultra
  namespace: observability
  labels:
    app: nrdot-collector
    profile: ultra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrdot-collector
      profile: ultra
  template:
    metadata:
      labels:
        app: nrdot-collector
        profile: ultra
    spec:
      serviceAccountName: nrdot-collector
      containers:
      - name: collector
        image: newrelic/nrdot-collector-host:1.1.0
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: NEW_RELIC_LICENSE_KEY
        - name: HOST_ROOT_PATH
          value: /hostfs
        - name: DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_METADATA_DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_DISPLAY_NAME
          value: "k8s-collector-ultra"
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: delta
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: zstd
        - name: NR_USE_ULTRA
          value: "true"
        - name: NR_USE_BALANCED
          value: "false"
        - name: NR_USE_OPTIMIZED
          value: "false"
        - name: NR_USE_LEAN
          value: "false"
        - name: NR_USE_MICRO
          value: "false"
        - name: MEM_LIMIT_MIB
          value: "256"
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: config
          mountPath: /etc/nrdot-collector-host/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          limits:
            memory: 320Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: hostfs
        hostPath:
          path: /
      - name: config
        configMap:
          name: nrdot-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrdot-collector-balanced
  namespace: observability
  labels:
    app: nrdot-collector
    profile: balanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrdot-collector
      profile: balanced
  template:
    metadata:
      labels:
        app: nrdot-collector
        profile: balanced
    spec:
      serviceAccountName: nrdot-collector
      containers:
      - name: collector
        image: newrelic/nrdot-collector-host:1.1.0
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: NEW_RELIC_LICENSE_KEY
        - name: HOST_ROOT_PATH
          value: /hostfs
        - name: DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_METADATA_DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_DISPLAY_NAME
          value: "k8s-collector-balanced"
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: delta
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: zstd
        - name: NR_USE_ULTRA
          value: "false"
        - name: NR_USE_BALANCED
          value: "true"
        - name: NR_USE_OPTIMIZED
          value: "false"
        - name: NR_USE_LEAN
          value: "false"
        - name: NR_USE_MICRO
          value: "false"
        - name: MEM_LIMIT_MIB
          value: "256"
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: config
          mountPath: /etc/nrdot-collector-host/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          limits:
            memory: 320Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: hostfs
        hostPath:
          path: /
      - name: config
        configMap:
          name: nrdot-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrdot-collector-optimized
  namespace: observability
  labels:
    app: nrdot-collector
    profile: optimized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrdot-collector
      profile: optimized
  template:
    metadata:
      labels:
        app: nrdot-collector
        profile: optimized
    spec:
      serviceAccountName: nrdot-collector
      containers:
      - name: collector
        image: newrelic/nrdot-collector-host:1.1.0
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: NEW_RELIC_LICENSE_KEY
        - name: HOST_ROOT_PATH
          value: /hostfs
        - name: DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_METADATA_DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_DISPLAY_NAME
          value: "k8s-collector-optimized"
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: delta
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: zstd
        - name: NR_USE_ULTRA
          value: "false"
        - name: NR_USE_BALANCED
          value: "false"
        - name: NR_USE_OPTIMIZED
          value: "true"
        - name: NR_USE_LEAN
          value: "false"
        - name: NR_USE_MICRO
          value: "false"
        - name: MEM_LIMIT_MIB
          value: "256"
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: config
          mountPath: /etc/nrdot-collector-host/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          limits:
            memory: 320Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: hostfs
        hostPath:
          path: /
      - name: config
        configMap:
          name: nrdot-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrdot-collector-lean
  namespace: observability
  labels:
    app: nrdot-collector
    profile: lean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrdot-collector
      profile: lean
  template:
    metadata:
      labels:
        app: nrdot-collector
        profile: lean
    spec:
      serviceAccountName: nrdot-collector
      containers:
      - name: collector
        image: newrelic/nrdot-collector-host:1.1.0
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: NEW_RELIC_LICENSE_KEY
        - name: HOST_ROOT_PATH
          value: /hostfs
        - name: DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_METADATA_DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_DISPLAY_NAME
          value: "k8s-collector-lean"
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: delta
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: zstd
        - name: NR_USE_ULTRA
          value: "false"
        - name: NR_USE_BALANCED
          value: "false"
        - name: NR_USE_OPTIMIZED
          value: "false"
        - name: NR_USE_LEAN
          value: "true"
        - name: NR_USE_MICRO
          value: "false"
        - name: MEM_LIMIT_MIB
          value: "256"
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: config
          mountPath: /etc/nrdot-collector-host/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          limits:
            memory: 320Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: hostfs
        hostPath:
          path: /
      - name: config
        configMap:
          name: nrdot-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrdot-collector-micro
  namespace: observability
  labels:
    app: nrdot-collector
    profile: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrdot-collector
      profile: micro
  template:
    metadata:
      labels:
        app: nrdot-collector
        profile: micro
    spec:
      serviceAccountName: nrdot-collector
      containers:
      - name: collector
        image: newrelic/nrdot-collector-host:1.1.0
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: NEW_RELIC_LICENSE_KEY
        - name: HOST_ROOT_PATH
          value: /hostfs
        - name: DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_METADATA_DEMO_ID
          value: "k8s-all-profiles"
        - name: NEW_RELIC_DISPLAY_NAME
          value: "k8s-collector-micro"
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: delta
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: zstd
        - name: NR_USE_ULTRA
          value: "false"
        - name: NR_USE_BALANCED
          value: "false"
        - name: NR_USE_OPTIMIZED
          value: "false"
        - name: NR_USE_LEAN
          value: "false"
        - name: NR_USE_MICRO
          value: "true"
        - name: MEM_LIMIT_MIB
          value: "256"
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: config
          mountPath: /etc/nrdot-collector-host/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          limits:
            memory: 320Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: hostfs
        hostPath:
          path: /
      - name: config
        configMap:
          name: nrdot-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrdot-collector
  namespace: observability