apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 90
      batch:
        timeout: 1s
        send_batch_size: 1000
      reservoir_sampler:
        size_k: 10000
        window_duration: 30s
        checkpoint_path: /var/otelpersist/badger
        checkpoint_interval: 5s
        trace_aware: true
        trace_buffer_timeout: 10s
        trace_buffer_max_size: 50000
        db_compaction_schedule_cron: "0 */6 * * *"
        db_compaction_target_size: 134217728 # 128 MiB

    exporters:
      logging:
        verbosity: detailed
      otlp:
        endpoint: "localhost:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, reservoir_sampler]
          exporters: [logging]
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: 0.0.0.0:8888

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: metrics
    port: 8888
    targetPort: 8888

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: badger-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: collector
        image: ghcr.io/deepaucksharma/nrdot-reservoir:bench
        args:
        - "--config=/etc/otelcol-reservoir/config.yaml"
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 8888
        volumeMounts:
        - name: config
          mountPath: /etc/otelcol-reservoir
        - name: badger-data
          mountPath: /var/otelpersist
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
      - name: badger-data
        persistentVolumeClaim:
          claimName: badger-data

---
apiVersion: batch/v1
kind: Job
metadata:
  name: trace-generator
spec:
  template:
    spec:
      containers:
      - name: tracegen
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/tracegen:latest
        args:
        - --otlp-endpoint=otel-collector:4317
        - --otlp-insecure
        - --duration=60s
        - --traces=10
        - --spans=50
      restartPolicy: Never
  backoffLimit: 1