apiVersion: v1
kind: Pod
metadata:
  name: reservoir-verify
spec:
  restartPolicy: Never
  containers:
  - name: verify
    image: reservoir-test:latest
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    volumeMounts:
    - name: badger-data
      mountPath: /var/otelpersist
  volumes:
  - name: badger-data
    emptyDir: {}