###############################################################################
# Trace-Aware Reservoir Processor Config for New Relic OTel Collector          #
###############################################################################

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  # Host metrics receiver for system metrics
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      load:
      disk:
      filesystem:
      network:
      paging:
      processes:
      process:
        mute_process_user_error: true
        mute_process_exe_error: true

processors:
  # Custom processor for trace-aware attributes - Simulated since we can't load it
  attributes/traceaware:
    actions:
      - key: processor.traceaware
        value: processed
        action: insert
      - key: processor.traceaware.version
        value: 1.0.0
        action: insert
      - key: collector.pipeline
        value: newrelic
        action: insert
  
  # Standard New Relic processors
  batch:
    send_batch_size: 1000
    timeout: 10s
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 200
    spike_limit_mib: 50
  
  resource:
    attributes:
      - key: service.name
        value: trace-aware-test
        action: insert
      - key: service.instance.id
        value: ${HOST_NAME}
        action: insert
  
  resourcedetection:
    detectors: [system, env]
    system:
      hostname_sources: [os]

exporters:
  # New Relic OTLP exporter
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}
    tls:
      insecure: false
  
  # Debug logging
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, resourcedetection, resource, attributes/traceaware, batch]
      exporters: [otlp, logging]