services:
  custom-nrdot:
    # Use official OpenTelemetry Collector Contrib image
    image: otel/opentelemetry-collector-contrib:latest
    container_name: custom-nrdot-collector
    ports:
      - "13133:13133"  # Health check
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    volumes:
      - /:/hostfs:ro # For hostmetrics
      - ./config-test.yaml:/etc/otel/config.yaml:ro
    env_file:
      - .env
    environment:
      # Entity Information
      - NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME=trace-aware-test
      - NEW_RELIC_METADATA_ENVIRONMENT=${OTEL_DEPLOYMENT_ENVIRONMENT:-production}
      - NEW_RELIC_METADATA_SERVICE_NAME=trace-aware-processor
    
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M