receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      load:
      disk:
      filesystem:
      network:
      paging:
      process:
        mute_process_name_error: true

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 250
    spike_limit_mib: 150
  
  # Using our custom prioritytagger processor to tag critical processes
  prioritytagger:
    critical_executables:
      - systemd
      - kubelet
      - dockerd
      - containerd
    critical_executable_patterns:
      - ".*java.*"
      - ".*node.*"
    cpu_steady_state_threshold: 0.5
    memory_rss_threshold_mib: 500
    priority_attribute_name: "nr.priority"
    critical_attribute_value: "critical"
    
  # We removed the filter processor since it's not available in our custom build
  
  # Using the attributes processor to add the Hello World message instead
  attributes:
    actions:
      - key: hello.processor
        value: "Hello from NRDOT Process-Metrics Optimization!"
        action: insert

exporters:
  otlphttp:
    endpoint: https://otlp.nr-data.net/v1/metrics
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
  
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: otelcol

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [prioritytagger, memory_limiter, attributes, batch]
      exporters: [otlphttp, prometheus]
  
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888