receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      load:
      disk:
      filesystem:
      network:
      paging:
      process:
        mute_process_name_error: true

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 250
    spike_limit_mib: 150
  
  # We can't use the prioritytagger as it's a custom processor.
  # Using filter processor to include only process metrics
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - process.cpu.time
          - process.cpu.utilization
          - process.memory.physical_usage
          - process.memory.virtual_usage
  
  # Using the attributes processor to add the Hello World message instead
  attributes:
    actions:
      - key: hello.processor
        value: "Hello from NRDOT Process-Metrics Optimization!"
        action: insert

exporters:
  otlphttp:
    endpoint: https://otlp.nr-data.net/v1/metrics
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
  
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: otelcol

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [filter, memory_limiter, attributes, batch]
      exporters: [otlphttp, prometheus]
  
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888