###############################################################################
# OpenTelemetry Configuration with Entity Synthesis Fixes                   #
###############################################################################

extensions:
  health_check: {}

###############################################################################
# 1. Receivers - Using standard hostmetrics                                  #
###############################################################################
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          # Added to align with New Relic expected metrics
          system.cpu.time:
            enabled: true
      memory:
        metrics:
          system.memory.usage:
            enabled: true
          # Added to align with New Relic expected metrics
          system.memory.utilization:
            enabled: true
      disk:
        metrics:
          system.disk.io:
            enabled: true
          # Added to align with New Relic disk metrics
          system.disk.operations:
            enabled: true
          system.disk.time:
            enabled: true
      filesystem:
        metrics:
          system.filesystem.usage:
            enabled: true
          system.filesystem.utilization:
            enabled: true
      load:
        metrics:
          system.cpu.load_average.1m:
            enabled: true
          system.cpu.load_average.5m:
            enabled: true
          system.cpu.load_average.15m:
            enabled: true
      network:
        metrics:
          system.network.io:
            enabled: true
          system.network.errors:
            enabled: true
          system.network.packets:
            enabled: true
      process:
        mute_process_user_error: true
        mute_process_exe_error: true
        metrics:
          # Keep original OTel metric names for compatibility
          process.cpu.utilization:
            enabled: true
          process.memory.usage:
            enabled: true
          process.memory.virtual:
            enabled: true
          process.disk.io:
            enabled: true
          process.handles:
            enabled: true
        include:
          match_type: regexp
          names:
            - ".*"
        exclude:
          match_type: regexp
          names:
            - "NOMATCH_PATTERN_XYZ"

###############################################################################
# 2. Processors                                                              #
###############################################################################
processors:
  # Memory Management
  memory_limiter:
    check_interval: 1s
    limit_mib: 250
    spike_limit_mib: 150
  
  # Resource detection - Critical for entity synthesis
  resourcedetection:
    detectors: [system, env]
    system:
      hostname_sources: ["os"]
      resource_attributes:
        host.id: {enabled: true}
        host.name: {enabled: true}
  
  # New Relic metric renaming/transforming to match dashboard expectations
  metricstransform:
    transforms:
      # CPU metrics - create process.cpu.pct from process.cpu.utilization
      - include: process.cpu.utilization
        action: update
        new_name: process.cpu.pct
        operations:
          - action: multiply
            new_value: 100
  
  # Process metrics attributes - ensure PID-level visibility
  filter/process_attributes:
    metrics:
      include:
        match_type: strict
        metric_names:
          - process.cpu.utilization
          - process.cpu.pct
          - process.memory.usage
          - process.memory.virtual
      attributes:
        - key: process.executable.name
          action: include
        - key: process.pid
          action: include
        - key: process.command
          action: include
  
  # Trace-aware attribute processor
  attributes:
    actions:
      # Critical for New Relic entity synthesis
      - key: instrumentation.name
        value: "opentelemetry"
        action: upsert
      - key: instrumentation.provider
        value: "opentelemetry"
        action: upsert
      - key: collector.name
        value: "trace-aware-collector"
        action: upsert
      # Custom trace attributes
      - key: trace.aware.collector
        value: "true"
        action: upsert
      - key: trace.aware.version
        value: "1.0"
        action: upsert
  
  # Resource attributes - critical for entity synthesis
  resource:
    attributes:
      # Entity synthesis attributes for New Relic
      - key: service.name
        value: "otel-collector-host"
        action: upsert
      - key: service.instance.id
        value: "otel-mac-instance"
        action: upsert
      - key: entity.type
        value: "HOST"
        action: upsert
      - key: entity.guid
        value: "${env:HOST_ID}" # Fall back to machine ID if not set
        action: upsert
      - key: deployment.environment
        value: "production"
        action: upsert
      - key: collector.profile
        value: "balanced"
        action: upsert
  
  # Temporality conversion - ensures proper delta metrics for New Relic
  cumulativetodelta:
    metrics:
      - process.cpu.pct
      - process.cpu.utilization
      - system.cpu.utilization
      - system.network.io
      - system.disk.io
  
  batch:
    send_batch_size: 1000
    timeout: 10s

###############################################################################
# 3. Exporters                                                               #
###############################################################################
exporters:
  otlphttp:
    endpoint: "https://otlp.nr-data.net"
    headers:
      api-key: "${env:NEW_RELIC_LICENSE_KEY}"
    compression: "gzip"
    timeout: 30s
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 5000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 5m

  debug:
    verbosity: detailed

###############################################################################
# 4. Service Configuration                                                   #
###############################################################################
service:
  telemetry:
    logs:
      level: "info"
      development: true
  
  extensions: [health_check]
  
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors:
        [memory_limiter,
         resourcedetection,
         metricstransform,
         filter/process_attributes,
         attributes,
         resource,
         cumulativetodelta,
         batch]
      exporters: [debug, otlphttp]