# Configuration Examples for Trace-Aware Reservoir Sampling

# Standard configuration for general usage
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
    
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25

  # Basic reservoir sampler configuration
  reservoir_sampler:
    # Maximum reservoir size (number of spans to keep)
    size_k: 5000
    
    # Duration of each sampling window
    window_duration: 60s
    
    # Path to the checkpoint file for persistence
    checkpoint_path: /var/lib/otelcol/reservoir_checkpoint.db
    
    # How often to write checkpoints
    checkpoint_interval: 10s
    
    # Enable trace-aware sampling
    trace_aware: true
    
    # Maximum traces to buffer at once (for trace-aware mode)
    trace_buffer_max_size: 100000
    
    # How long to wait for a trace to complete
    trace_buffer_timeout: 10s
    
    # Optional: Cron schedule for database compaction
    db_compaction_schedule_cron: "0 0 * * *"  # Daily at midnight
    
    # Optional: Target size for database after compaction (bytes)
    db_compaction_target_size: 104857600  # 100MB

exporters:
  debug:
    verbosity: detailed

  otlphttp:
    endpoint: "https://otlp.nr-data.net:4318"
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, reservoir_sampler]
      exporters: [debug, otlphttp]

  telemetry:
    metrics:
      level: detailed

---
# High-volume configuration for production environments
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64
        max_concurrent_streams: 1000
      http:
        endpoint: 0.0.0.0:4318
        max_request_body_size: 64_000_000

processors:
  batch:
    send_batch_size: 2000
    timeout: 5s
    
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25

  # High-volume reservoir sampler configuration
  reservoir_sampler:
    # Larger reservoir size for more samples
    size_k: 10000
    
    # Shorter window to handle higher volume
    window_duration: 30s
    
    # Path to the checkpoint file
    checkpoint_path: /var/lib/otelcol/reservoir_checkpoint.db
    
    # More frequent checkpoints for better durability
    checkpoint_interval: 15s
    
    # Enable trace-aware sampling
    trace_aware: true
    
    # Larger trace buffer for high concurrency
    trace_buffer_max_size: 200000
    
    # Shorter timeout to process traces faster
    trace_buffer_timeout: 5s
    
    # More frequent compaction for high volume
    db_compaction_schedule_cron: "0 */6 * * *"  # Every 6 hours
    
    # Larger target size for production workloads
    db_compaction_target_size: 209715200  # 200MB

exporters:
  otlphttp:
    endpoint: "https://otlp.nr-data.net:4318"
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    timeout: 30s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, reservoir_sampler]
      exporters: [otlphttp]

  telemetry:
    metrics:
      level: detailed

---
# Low-resource configuration for edge devices or sidecars
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 500
    timeout: 15s
    
  memory_limiter:
    check_interval: 1s
    limit_percentage: 70
    spike_limit_percentage: 20

  # Low-resource reservoir sampler configuration
  reservoir_sampler:
    # Smaller reservoir size for lower memory usage
    size_k: 1000
    
    # Longer window for lower CPU usage
    window_duration: 120s
    
    # Path to the checkpoint file
    checkpoint_path: /var/lib/otelcol/reservoir_checkpoint.db
    
    # Less frequent checkpoints to reduce I/O
    checkpoint_interval: 30s
    
    # Enable trace-aware sampling
    trace_aware: true
    
    # Smaller trace buffer for lower memory usage
    trace_buffer_max_size: 20000
    
    # Longer timeout to reduce processing frequency
    trace_buffer_timeout: 20s
    
    # Less frequent compaction to reduce I/O and CPU usage
    db_compaction_schedule_cron: "0 0 * * 0"  # Weekly on Sunday
    
    # Smaller target size for edge devices
    db_compaction_target_size: 52428800  # 50MB

exporters:
  otlphttp:
    endpoint: "https://otlp.nr-data.net:4318"
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, reservoir_sampler]
      exporters: [otlphttp]

  telemetry:
    metrics:
      level: basic