dist:
  name: traceaware-otelcol
  description: "Custom OpenTelemetry Collector with Trace-Aware Reservoir Processor"
  version: "0.1.0"
  otelcol_version: "0.80.0"  # Using a more compatible version

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.80.0
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.80.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.80.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.80.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.80.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.80.0
  - gomod: github.com/deepaksharma/traceawarereservoir/processor v0.0.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/healthcheckextension v0.80.0

replaces:
  - github.com/deepaksharma/traceawarereservoir/processor v0.0.0 => /build/processor