apiVersion: v2
name: reservoir
description: A Helm chart for the Trace-Aware Reservoir Sampling OpenTelemetry Collector
type: application
version: 0.1.0
appVersion: 0.1.0
maintainers:
  - name: deepaucksharma
    url: https://github.com/deepaucksharma/trace-aware-reservoir-otel
keywords:
  - opentelemetry
  - collector
  - sampling
  - tracing
home: https://github.com/deepaucksharma/trace-aware-reservoir-otel
icon: https://opentelemetry.io/img/logos/opentelemetry-icon-color.png
