# Default values for the reservoir chart

image:
  repository: ghcr.io/deepaucksharma/nrdot-reservoir
  tag: v0.1.0  # This will be overridden by CI

# Global values shared across charts
global:
  licenseKey: ""  # New Relic license key
  cluster: "reservoir-demo"

# Collector configuration
collector:
  configOverride:
    processors:
      reservoir_sampler:
        size_k: 5000                # Reservoir size (in thousands of traces)
        window_duration: 60s        # Time window for each reservoir
        checkpoint_path: /var/otelpersist/badger  # Persistence location
        checkpoint_interval: 10s    # How often to save state
        trace_aware: true           # Buffer spans from the same trace
        trace_buffer_timeout: 30s   # How long to wait for spans from same trace
        trace_buffer_max_size: 100000  # Maximum buffer size
        db_compaction_schedule_cron: "0 2 * * *"  # When to compact the database
        db_compaction_target_size: 134217728  # Target size for compaction (128 MiB)
    exporters:
      otlphttp:
        endpoint: https://otlp.nr-data.net:4318
    service:
      pipelines:
        traces:
          processors: [memory_limiter, batch, reservoir_sampler]
          exporters: [otlphttp]

# Persistence configuration
persistence:
  enabled: true
  size: 2Gi
  fsGroup: 10001  # UID for the collector process, must match container user

# Resource requirements
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 400Mi
