apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-collector-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 90

      batch:
        timeout: 1s
        send_batch_size: 1024

      reservoir_sampler:
        size_k: {{ .Values.collector.configOverride.processors.reservoir_sampler.size_k }}
        window_duration: {{ .Values.collector.configOverride.processors.reservoir_sampler.window_duration }}
        checkpoint_path: {{ .Values.collector.configOverride.processors.reservoir_sampler.checkpoint_path }}
        checkpoint_interval: {{ .Values.collector.configOverride.processors.reservoir_sampler.checkpoint_interval }}
        trace_aware: {{ .Values.collector.configOverride.processors.reservoir_sampler.trace_aware }}
        trace_buffer_timeout: {{ .Values.collector.configOverride.processors.reservoir_sampler.trace_buffer_timeout | default "30s" }}
        trace_buffer_max_size: {{ .Values.collector.configOverride.processors.reservoir_sampler.trace_buffer_max_size | default 100000 }}
        db_compaction_schedule_cron: {{ .Values.collector.configOverride.processors.reservoir_sampler.db_compaction_schedule_cron | default "0 2 * * *" }}
        db_compaction_target_size: {{ .Values.collector.configOverride.processors.reservoir_sampler.db_compaction_target_size | default 134217728 }}

    exporters:
      otlphttp:
        endpoint: {{ .Values.collector.configOverride.exporters.otlphttp.endpoint | default "https://otlp.nr-data.net:4318" }}
        headers:
          api-key: {{ .Values.global.licenseKey }}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: {{ .Values.collector.configOverride.service.pipelines.traces.processors | default "[memory_limiter, batch, reservoir_sampler]" }}
          exporters: {{ .Values.collector.configOverride.service.pipelines.traces.exporters | default "[otlphttp]" }}

      telemetry:
        metrics:
          address: 0.0.0.0:8888
