apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
