apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nrdot-collector-host
  namespace: observability
spec:
  template:
    spec:
      containers:
      - name: collector
        env:
        - name: PROFILE
          value: "micro"
        - name: NR_USE_ULTRA
          value: "false"
        - name: NR_USE_BALANCED
          value: "false"
        - name: NR_USE_OPTIMIZED
          value: "false"
        - name: NR_USE_LEAN
          value: "false"
        - name: NR_USE_MICRO
          value: "true"