apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nrdot-collector-host
  namespace: observability
  labels:
    app: nrdot-collector-host
spec:
  selector:
    matchLabels:
      app: nrdot-collector-host
  template:
    metadata:
      labels:
        app: nrdot-collector-host
    spec:
      serviceAccountName: nrdot-collector
      containers:
      - name: collector
        image: newrelic/nrdot-collector-host:1.1.0
        securityContext:
          runAsUser: 0
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: NEW_RELIC_LICENSE_KEY
        - name: HOST_ROOT_PATH
          value: /hostfs
        # Demo metadata
        - name: DEMO_ID
          value: "k8s-$(NODE_NAME)"
        - name: NEW_RELIC_METADATA_DEMO_ID
          value: "k8s-$(NODE_NAME)"
        - name: NEW_RELIC_DISPLAY_NAME
          value: "k8s-$(NODE_NAME)-$(PROFILE)"
        # Global OTEL settings
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: delta
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: zstd
        # Profile selection - will be overridden by overlays
        - name: PROFILE
          value: "balanced"
        - name: NR_USE_ULTRA
          value: "false"
        - name: NR_USE_BALANCED
          value: "true"
        - name: NR_USE_OPTIMIZED
          value: "false"
        - name: NR_USE_LEAN
          value: "false"
        - name: NR_USE_MICRO
          value: "false"
        # Resource and threshold settings
        - name: MEM_LIMIT_MIB
          value: "100"
        - name: IDLE_CPU_THRESHOLD
          value: "0.005"
        - name: IDLE_RSS_THRESHOLD
          value: "31457280"
        - name: IDLE_CPU_THRESHOLD_LEAN_MICRO
          value: "0.05"
        - name: IDLE_RSS_THRESHOLD_LEAN_MICRO
          value: "52428800"
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: config
          mountPath: /etc/nrdot-collector-host/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          limits:
            memory: 320Mi
          requests:
            cpu: 100m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 10
          periodSeconds: 20
      volumes:
      - name: hostfs
        hostPath:
          path: /
      - name: config
        configMap:
          name: nrdot-collector-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrdot-collector
  namespace: observability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrdot-collector-config
  namespace: observability
data:
  config.yaml: |
    # This content will be replaced by the ConfigMap at runtime
    # For the actual configuration, look at the modified config.yaml
    # in the repository root.