###############################################################################
# Simple Hello World Processor Configuration                                #
###############################################################################

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  # Host metrics receiver
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      load:

processors:
  # Memory limiter
  memory_limiter:
    check_interval: 1s
    limit_mib: 100
    spike_limit_mib: 50

  # Resource detection
  resourcedetection:
    detectors: [system, env]

  # Hello World processor
  hello:
    message: "Hello from OpenTelemetry!"

  # Batch processor
  batch:
    timeout: 5s

exporters:
  # Logging exporter for local testing
  logging:
    verbosity: detailed
    sampling_initial: 5

service:
  telemetry:
    logs:
      level: info
      development: true
      encoding: console
      
  extensions: [health_check]
  
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, resourcedetection, hello, batch]
      exporters: [logging]