# High-Volume Environment Configuration
# For environments with high trace volumes (100K+ spans per second)

# Larger reservoir size for more comprehensive sampling
size_k: 10000

# Shorter window for more frequent updates
window_duration: "30s"

# More frequent checkpoints for better durability
checkpoint_interval: "15s"

# Keep entire traces together
trace_aware: true

# Larger buffer for handling more concurrent traces
trace_buffer_max_size: 200000

# Shorter timeout to prevent buffer overflow
trace_buffer_timeout: "15s"

# Weekly compaction at low-traffic time
db_compaction_schedule_cron: "0 2 * * 0"

# Kubernetes Settings
persistence:
  enabled: true
  size: 5Gi

checkpoint_path: "/var/otelpersist/reservoir.db"