# Low-Resource Environment Configuration
# For resource-constrained environments or testing

# Smaller reservoir size to reduce memory usage
size_k: 1000

# Longer window to reduce processing overhead
window_duration: "120s"

# Less frequent checkpoints to reduce I/O
checkpoint_interval: "30s"

# Keep entire traces together
trace_aware: true

# Smaller buffer to limit memory consumption
trace_buffer_max_size: 20000

# Longer timeout to accommodate slower systems
trace_buffer_timeout: "45s"

# Weekly compaction at low-traffic time
db_compaction_schedule_cron: "0 2 * * 0"

# Kubernetes Settings
persistence:
  enabled: true
  size: 500Mi

checkpoint_path: "/var/otelpersist/reservoir.db"