# Balanced Configuration
# General-purpose settings for most environments

# Moderate reservoir size
size_k: 5000

# Balanced window duration
window_duration: "60s"

# Moderate checkpoint frequency
checkpoint_interval: "10s"

# Keep entire traces together
trace_aware: true

# Moderate buffer size
trace_buffer_max_size: 100000

# Standard timeout
trace_buffer_timeout: "30s"

# Weekly compaction at low-traffic time
db_compaction_schedule_cron: "0 2 * * 0"

# Kubernetes Settings
persistence:
  enabled: true
  size: 1Gi

checkpoint_path: "/var/otelpersist/reservoir.db"