name: Build and Publish NR-DOT with Reservoir Sampler

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Clone NR-DOT repository
        run: |
          git clone https://github.com/newrelic/opentelemetry-collector-releases.git
          cd opentelemetry-collector-releases
          git checkout -b feat/reservoir-sampler
          
      - name: Update manifests
        run: |
          # Update the manifest to include our processor
          # Example - adjust based on your actual needs
          cat > manifest.patch << EOF
          processors:
            # existing processors...
            - gomod: github.com/your-org/trace-aware-reservoir-otel/internal/processor/reservoirsampler v0.1.0
          EOF
          
          # Apply the patch - modify this as needed for your specific manifest file
          cd opentelemetry-collector-releases
          # Example of updating the manifest - adjust path as needed
          sed -i '/processors:/r ../manifest.patch' distributions/nrdot-collector-k8s/manifest.yaml 
          
      - name: Build distribution
        run: |
          cd opentelemetry-collector-releases
          make dist
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/nrdot-reservoir
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=short
            type=ref,event=branch
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: opentelemetry-collector-releases/_dist/nrdot/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
