name: End-to-End Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - throughput
          - latency
          - durability
          - resource
          - trace

jobs:
  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          go mod tidy
          go mod verify

      - name: Build Collector
        run: make build

      - name: Run Integration Tests
        run: make integration-tests

      - name: Run E2E tests
        run: |
          case "${{ github.event.inputs.test_type }}" in
            all)
              make e2e-tests
              ;;
            throughput)
              go test -v -timeout=15m ./e2e/tests -run TestThroughput
              ;;
            latency)
              go test -v -timeout=15m ./e2e/tests -run TestLatency
              ;;
            durability)
              go test -v -timeout=15m ./e2e/tests -run TestDurability
              ;;
            resource)
              go test -v -timeout=15m ./e2e/tests -run TestResourceUsage
              ;;
            trace)
              go test -v -timeout=15m ./e2e/tests -run TestTracePreservation
              ;;
          esac